Workaround nunjucks bugs.
Nunjucks from 3.0.0 to at least 3.1.3 contains few extension-related bugs.

1. Reading wrong (renamed) property in CallExtension that is expected to be
set in env.addExtension. Caused resulting template to try to call extension
named "[object Object]" which in turn fails and keeps templates
from rendering.
2. Taking a function from an instance to a variable "is not" allowed in
strict code and causes this-pointer to be undefined. Add a compatibility
layer that changes the sloppy function handling to work in strict code.
ES15 classes are always strict. Caused preprocessing to throw
TypeError: Cannot set property 'currentName' of undefined.

Not fixed: preprocess does not get name argument anymore. It was removed
in a code style fix commit (that also caused #2)...