Fix code formatting in item dump.
Since a2d4d2f2fc5b0be87205a789ac261d84cf10a29f non-representative box
items do not have a barcode and have it set to None.
Should fix following:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 184, in handle_request
    for item in respiter:
  File "/usr/src/app/kirppu/views/csv_utils.py", line 30, in streamer
    for a_string in generator(output):
  File "/usr/src/app/kirppu/views/item_dump.py", line 115, in item_dump
    writer.writerow(_process_column(item, c, as_text) for c in COLUMNS)
  File "/usr/src/app/kirppu/views/item_dump.py", line 75, in writerow
    self._output.write(self._pattern.format(*columns))
TypeError: unsupported format string passed to NoneType.__format__